services:
  # dp-server:
  #   build: ./disease-predictor-back-end
  #   image: dp-server:0.0.1
  #   ports:
  #     - 5000:5000
  #   restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped
